/* Auto generated by 'npm run gen-proto' */
export const MemberResolvers = {
  GeoLocation: {
  },
  MetricIdentifier: {
  },
  MetricSeries: {
    data_type(metricseries) {
      return metricseries.data_type;
    },
    tag_meta(metricseries) {
      return metricseries.tag_meta;
    },
    dedupe_strategy(metricseries) {
      return metricseries.dedupe_strategy;
    },
  },
  MetricTagMeta: {
    index(metrictagmeta) {
      return metrictagmeta.index;
    },
  },
  MetricDatapoint: {
    location(metricdatapoint) {
      return metricdatapoint.location;
    },
  },
  MetricDatapointWithMeta: {
    datapoint(metricdatapointwithmeta) {
      return metricdatapointwithmeta.datapoint;
    },
    metric(metricdatapointwithmeta) {
      return metricdatapointwithmeta.metric;
    },
  },
  MetricDatapointQuery: {
    time_constraint(metricdatapointquery) {
      return metricdatapointquery.time_constraint;
    },
    tag_constraint(metricdatapointquery) {
      return metricdatapointquery.tag_constraint;
    },
  },
  MetricDatapointTimeConstraint: {
  },
  MetricDatapointTagConstraint: {
    tags(metricdatapointtagconstraint) {
      return metricdatapointtagconstraint.tags;
    },
  },
  MetricDatapointTagConstraintTag: {
  },
  RequestContext: {
    identifier(requestcontext) {
      return requestcontext.identifier;
    },
  },
  RecordDatapointRequest: {
    context(recorddatapointrequest) {
      return recorddatapointrequest.context;
    },
    datapoint(recorddatapointrequest) {
      return recorddatapointrequest.datapoint;
    },
  },
  RecordDatapointResponse: {
    rejected(recorddatapointresponse) {
      return recorddatapointresponse.rejected;
    },
  },
  ListDatapointRequest: {
    query(listdatapointrequest) {
      return listdatapointrequest.query;
    },
    context(listdatapointrequest) {
      return listdatapointrequest.context;
    },
  },
  ListDatapointResponse: {
    response_type(listdatapointresponse) {
      return listdatapointresponse.response_type;
    },
    datapoint(listdatapointresponse) {
      return listdatapointresponse.datapoint;
    },
    series(listdatapointresponse) {
      return listdatapointresponse.series;
    },
  },
  ListMetricResponse: {
    metric(listmetricresponse) {
      return listmetricresponse.metric;
    },
  },
  CreateMetricRequest: {
    metric(createmetricrequest) {
      return createmetricrequest.metric;
    },
  },
  CreateMetricResponse: {
    metric(createmetricresponse) {
      return createmetricresponse.metric;
    },
  },
  GetMetricRequest: {
    context(getmetricrequest) {
      return getmetricrequest.context;
    },
  },
  GetMetricResponse: {
    metric(getmetricresponse) {
      return getmetricresponse.metric;
    },
  },
  HttpRule: {
    custom(httprule) {
      return httprule.custom;
    },
    additional_bindings(httprule) {
      return httprule.additional_bindings;
    },
  },
  CustomHttpPattern: {
  },
  MSClientMessage: {
    metric_subscribe(msclientmessage) {
      return msclientmessage.metric_subscribe;
    },
    metric_unsubscribe(msclientmessage) {
      return msclientmessage.metric_unsubscribe;
    },
  },
  MSServerMessage: {
    subscribe_result(msservermessage) {
      return msservermessage.subscribe_result;
    },
    unsubscribe_result(msservermessage) {
      return msservermessage.unsubscribe_result;
    },
  },
  MSSubscribe: {
    context(mssubscribe) {
      return mssubscribe.context;
    },
    query(mssubscribe) {
      return mssubscribe.query;
    },
  },
  MSSubscribeResult: {
    error(mssubscriberesult) {
      return mssubscriberesult.error;
    },
  },
  MSUnsubscribe: {
  },
  MSUnsubscribeResult: {
  },
};
